bismark_index:
  /home/groups/CEDAR/anno/indices/bismark/bowtie2/hg38/
project_id:
  PT29
trim_dir:
  samples/trim
map_dir:
  bismarkSE
acc_prom:
  1000
met_prom:
  10000
gtf_file:
  /home/groups/CEDAR/anno/gtf/hg38_ens94.chr.gtf
accBed:
  data/anno/promoters1000.bed
metBed:
  data/anno/promoters10000.bed
bedtools:
  /home/groups/CEDAR/tools/bedtools
cpg:
  /home/groups/CEDAR/anno/UCSC/hg38/cpgIslandExt.hg38.bed
annoDir:
  data/anno
min_cells_acc:
  5
min_cells_met:
  5
accCov:
  100000
metCov:
  100000
accMeanTop:
  45
accMeanBot:
  20
seq_type:
  PE
